// Code generated by protoc-gen-go. DO NOT EDIT.
// source: search.proto

package search

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type Item struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Brand                string   `protobuf:"bytes,3,opt,name=brand" json:"brand,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price" json:"price,omitempty"`
	UserId               string   `protobuf:"bytes,5,opt,name=userId" json:"userId,omitempty"`
	UserName             string   `protobuf:"bytes,6,opt,name=userName" json:"userName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_447ba5cc4002110c, []int{0}
}
func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (dst *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(dst, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *Item) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Item) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Item) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type SearchFilter struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchFilter) Reset()         { *m = SearchFilter{} }
func (m *SearchFilter) String() string { return proto.CompactTextString(m) }
func (*SearchFilter) ProtoMessage()    {}
func (*SearchFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_search_447ba5cc4002110c, []int{1}
}
func (m *SearchFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchFilter.Unmarshal(m, b)
}
func (m *SearchFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchFilter.Marshal(b, m, deterministic)
}
func (dst *SearchFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchFilter.Merge(dst, src)
}
func (m *SearchFilter) XXX_Size() int {
	return xxx_messageInfo_SearchFilter.Size(m)
}
func (m *SearchFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchFilter.DiscardUnknown(m)
}

var xxx_messageInfo_SearchFilter proto.InternalMessageInfo

func (m *SearchFilter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Item)(nil), "search.Item")
	proto.RegisterType((*SearchFilter)(nil), "search.SearchFilter")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SearchApi service

type SearchApiClient interface {
	GetItemByName(ctx context.Context, in *SearchFilter, opts ...grpc.CallOption) (SearchApi_GetItemByNameClient, error)
}

type searchApiClient struct {
	cc *grpc.ClientConn
}

func NewSearchApiClient(cc *grpc.ClientConn) SearchApiClient {
	return &searchApiClient{cc}
}

func (c *searchApiClient) GetItemByName(ctx context.Context, in *SearchFilter, opts ...grpc.CallOption) (SearchApi_GetItemByNameClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_SearchApi_serviceDesc.Streams[0], c.cc, "/search.SearchApi/GetItemByName", opts...)
	if err != nil {
		return nil, err
	}
	x := &searchApiGetItemByNameClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SearchApi_GetItemByNameClient interface {
	Recv() (*Item, error)
	grpc.ClientStream
}

type searchApiGetItemByNameClient struct {
	grpc.ClientStream
}

func (x *searchApiGetItemByNameClient) Recv() (*Item, error) {
	m := new(Item)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for SearchApi service

type SearchApiServer interface {
	GetItemByName(*SearchFilter, SearchApi_GetItemByNameServer) error
}

func RegisterSearchApiServer(s *grpc.Server, srv SearchApiServer) {
	s.RegisterService(&_SearchApi_serviceDesc, srv)
}

func _SearchApi_GetItemByName_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SearchApiServer).GetItemByName(m, &searchApiGetItemByNameServer{stream})
}

type SearchApi_GetItemByNameServer interface {
	Send(*Item) error
	grpc.ServerStream
}

type searchApiGetItemByNameServer struct {
	grpc.ServerStream
}

func (x *searchApiGetItemByNameServer) Send(m *Item) error {
	return x.ServerStream.SendMsg(m)
}

var _SearchApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "search.SearchApi",
	HandlerType: (*SearchApiServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetItemByName",
			Handler:       _SearchApi_GetItemByName_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "search.proto",
}

func init() { proto.RegisterFile("search.proto", fileDescriptor_search_447ba5cc4002110c) }

var fileDescriptor_search_447ba5cc4002110c = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0x4d, 0x2c,
	0x4a, 0xce, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xba, 0x18, 0xb9,
	0x58, 0x3c, 0x4b, 0x52, 0x73, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0x98, 0x32, 0x53, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x98, 0xc0,
	0x22, 0x60, 0xb6, 0x90, 0x08, 0x17, 0x6b, 0x52, 0x51, 0x62, 0x5e, 0x8a, 0x04, 0x33, 0x58, 0x10,
	0xc2, 0x01, 0x89, 0x16, 0x14, 0x65, 0x26, 0xa7, 0x4a, 0xb0, 0x28, 0x30, 0x6a, 0x30, 0x05, 0x41,
	0x38, 0x42, 0x62, 0x5c, 0x6c, 0xa5, 0xc5, 0xa9, 0x45, 0x9e, 0x29, 0x12, 0xac, 0x60, 0xc5, 0x50,
	0x9e, 0x90, 0x14, 0x17, 0x07, 0x88, 0xe5, 0x07, 0x32, 0x9b, 0x0d, 0x2c, 0x03, 0xe7, 0x2b, 0x29,
	0x71, 0xf1, 0x04, 0x83, 0x9d, 0xe5, 0x96, 0x99, 0x53, 0x92, 0x5a, 0x04, 0x77, 0x03, 0x23, 0xc2,
	0x0d, 0x46, 0x2e, 0x5c, 0x9c, 0x10, 0x35, 0x8e, 0x05, 0x99, 0x42, 0xe6, 0x5c, 0xbc, 0xee, 0xa9,
	0x25, 0x20, 0xf7, 0x3b, 0x55, 0xfa, 0x81, 0x5d, 0xa8, 0x07, 0xf5, 0x25, 0xb2, 0x39, 0x52, 0x3c,
	0x30, 0x51, 0x90, 0x4a, 0x25, 0x06, 0x03, 0xc6, 0x24, 0x36, 0x70, 0x28, 0x18, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x8f, 0x60, 0xdd, 0xb0, 0x15, 0x01, 0x00, 0x00,
}
